_classes_ = [
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
]
_dim_ = 256
_ffn_dim_ = 512
_modality_ = dict(
    use_camera=True,
    use_external=True,
    use_lidar=False,
    use_map=False,
    use_radar=False)
_num_levels_ = 4
_pos_dim_ = 128
bev_h_ = 200
bev_w_ = 200
checkpoint_config = dict(interval=1)
class_names = [
    'car',
    'truck',
    'construction_vehicle',
    'bus',
    'trailer',
    'barrier',
    'motorcycle',
    'bicycle',
    'pedestrian',
    'traffic_cone',
]
custom_hooks = []
custom_imports = dict(
    allow_failed_imports=False,
    imports=[
        'projects.mmdet3d_plugin',
        'projects.mmdet3d_plugin.datasets.nuscenes_dataset',
        'projects.mmdet3d_plugin.datasets.pipelines.transform_3d',
        'projects.mmdet3d_plugin.bevformer.detectors.bevformer',
        'projects.mmdet3d_plugin.bevformer.dense_heads.bevformer_head',
        'projects.mmdet3d_plugin.bevformer.modules.transformer',
        'projects.mmdet3d_plugin.bevformer.modules.encoder',
        'projects.mmdet3d_plugin.bevformer.modules.decoder',
        'projects.mmdet3d_plugin.bevformer.modules.spatial_cross_attention',
        'projects.mmdet3d_plugin.bevformer.modules.temporal_self_attention',
        'projects.mmdet3d_plugin.bevformer.hooks.adapter_debug_hook',
        'projects.mmdet3d_plugin.core.bbox.assigners.hungarian_assigner_3d',
        'projects.mmdet3d_plugin.core.bbox.coders.nms_free_coder',
        'projects.mmdet3d_plugin.core.bbox.match_costs.match_cost',
        'projects.mmdet3d_plugin.bevformer_nuscenes_metric',
    ])
data = dict(
    nonshuffler_sampler=dict(type='DistributedSampler'),
    samples_per_gpu=1,
    shuffler_sampler=dict(type='DistributedGroupSampler'),
    test=dict(
        ann_file='data/nuscenes/nuscenes_infos_temporal_val.pkl',
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        data_root='data/nuscenes/',
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        pipeline=[
            dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    1.0,
                    1.0,
                    1.0,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                flip=False,
                img_scale=(
                    1600,
                    900,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        class_names=[
                            'car',
                            'truck',
                            'construction_vehicle',
                            'bus',
                            'trailer',
                            'barrier',
                            'motorcycle',
                            'bicycle',
                            'pedestrian',
                            'traffic_cone',
                        ],
                        type='DefaultFormatBundle3D',
                        with_label=False),
                    dict(keys=[
                        'img',
                    ], type='CustomCollect3D'),
                ],
                type='MultiScaleFlipAug3D'),
        ],
        test_mode=True,
        type='CustomNuScenesDataset'),
    train=dict(
        ann_file='data/nuscenes/nuscenes_infos_temporal_train.pkl',
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        data_root='data/nuscenes/',
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        pipeline=[
            dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
            dict(type='PhotoMetricDistortionMultiViewImage'),
            dict(
                type='LoadAnnotations3D',
                with_attr_label=False,
                with_bbox_3d=True,
                with_label_3d=True),
            dict(
                point_cloud_range=[
                    -51.2,
                    -51.2,
                    -5.0,
                    51.2,
                    51.2,
                    3.0,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    1.0,
                    1.0,
                    1.0,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                class_names=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='DefaultFormatBundle3D'),
            dict(
                keys=[
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                    'img',
                ],
                type='CustomCollect3D'),
        ],
        queue_length=4,
        test_mode=False,
        type='CustomNuScenesDataset',
        use_valid_flag=True),
    val=dict(
        ann_file='data/nuscenes/nuscenes_infos_temporal_val.pkl',
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        data_root='data/nuscenes/',
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        pipeline=[
            dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    1.0,
                    1.0,
                    1.0,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                flip=False,
                img_scale=(
                    1600,
                    900,
                ),
                pts_scale_ratio=1,
                transforms=[
                    dict(
                        class_names=[
                            'car',
                            'truck',
                            'construction_vehicle',
                            'bus',
                            'trailer',
                            'barrier',
                            'motorcycle',
                            'bicycle',
                            'pedestrian',
                            'traffic_cone',
                        ],
                        type='DefaultFormatBundle3D',
                        with_label=False),
                    dict(keys=[
                        'img',
                    ], type='CustomCollect3D'),
                ],
                type='MultiScaleFlipAug3D'),
        ],
        samples_per_gpu=1,
        test_mode=True,
        type='CustomNuScenesDataset'),
    workers_per_gpu=4)
data_root = 'C:/datasets/nuscenes/'
dataset_type = 'CustomNuScenesDataset'
default_hooks = dict(
    checkpoint=dict(interval=1, max_keep_ckpts=4, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'))
default_scope = 'mmdet3d'
dist_params = dict(backend='nccl')
eval_pipeline = [
    dict(
        coord_type='LIDAR',
        file_client_args=dict(backend='disk'),
        load_dim=5,
        type='LoadPointsFromFile',
        use_dim=5),
    dict(
        file_client_args=dict(backend='disk'),
        sweeps_num=10,
        type='LoadPointsFromMultiSweeps'),
    dict(
        class_names=[
            'car',
            'truck',
            'trailer',
            'bus',
            'construction_vehicle',
            'bicycle',
            'motorcycle',
            'pedestrian',
            'traffic_cone',
            'barrier',
        ],
        type='DefaultFormatBundle3D',
        with_label=False),
    dict(keys=[
        'points',
    ], type='Collect3D'),
]
evaluation = dict(
    interval=1,
    pipeline=[
        dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
        dict(
            mean=[
                103.53,
                116.28,
                123.675,
            ],
            std=[
                1.0,
                1.0,
                1.0,
            ],
            to_rgb=False,
            type='NormalizeMultiviewImage'),
        dict(size_divisor=32, type='PadMultiViewImage'),
        dict(
            flip=False,
            img_scale=(
                1600,
                900,
            ),
            pts_scale_ratio=1,
            transforms=[
                dict(
                    class_names=[
                        'car',
                        'truck',
                        'construction_vehicle',
                        'bus',
                        'trailer',
                        'barrier',
                        'motorcycle',
                        'bicycle',
                        'pedestrian',
                        'traffic_cone',
                    ],
                    type='DefaultFormatBundle3D',
                    with_label=False),
                dict(keys=[
                    'img',
                ], type='CustomCollect3D'),
            ],
            type='MultiScaleFlipAug3D'),
    ])
file_client_args = dict(backend='disk')
img_norm_cfg = dict(
    mean=[
        103.53,
        116.28,
        123.675,
    ], std=[
        1.0,
        1.0,
        1.0,
    ], to_rgb=False)
input_modality = dict(
    use_camera=True,
    use_external=True,
    use_lidar=False,
    use_map=False,
    use_radar=False)
launcher = 'none'
load_from = 'E:/bev_research/work_dirs/e6_depth_scale_channels/epoch_4.pth'
log_config = dict(
    hooks=[
        dict(type='TextLoggerHook'),
        dict(type='TensorboardLoggerHook'),
    ],
    interval=50)
log_level = 'INFO'
lr_config = dict(
    min_lr_ratio=0.001,
    policy='CosineAnnealing',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333)
model = dict(
    depth_adapter=dict(
        adapter_hidden_ratio=1.0,
        ckpt_path='E:/bev_research/checkpoints/depth_anything_v2_vits.pth',
        consistency_aug=dict(
            brightness=0.4, contrast=0.4, hue=0.1, saturation=0.3),
        consistency_weight=0.0,
        dav2_encoder='vits',
        depth_repo_path='E:/Auto_Image/bev_research/Depth-Anything-V2',
        enabled=True,
        feature_channels=[
            256,
            256,
            256,
            256,
        ],
        inject_levels=[
            0,
        ],
        input_size=308,
        intermediate_layers=[
            11,
        ],
        residual_scale=0.1,
        use_amp=True),
    freeze_bevformer=True,
    img_backbone=dict(
        dcn=dict(deform_groups=1, fallback_on_stride=False, type='DCNv2'),
        depth=101,
        frozen_stages=1,
        norm_cfg=dict(requires_grad=False, type='BN2d'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            1,
            2,
            3,
        ),
        stage_with_dcn=(
            False,
            False,
            True,
            True,
        ),
        style='caffe',
        type='mmdet.ResNet',
        with_cp=True),
    img_neck=dict(
        add_extra_convs='on_output',
        in_channels=[
            512,
            1024,
            2048,
        ],
        num_outs=4,
        out_channels=256,
        relu_before_extra_convs=True,
        start_level=0,
        type='mmdet.FPN'),
    pts_bbox_head=dict(
        as_two_stage=False,
        bbox_coder=dict(
            max_num=300,
            num_classes=10,
            pc_range=[
                -51.2,
                -51.2,
                -5.0,
                51.2,
                51.2,
                3.0,
            ],
            post_center_range=[
                -61.2,
                -61.2,
                -10.0,
                61.2,
                61.2,
                10.0,
            ],
            type='NMSFreeCoder',
            voxel_size=[
                0.2,
                0.2,
                8,
            ]),
        bev_h=200,
        bev_w=200,
        in_channels=256,
        loss_bbox=dict(loss_weight=0.25, type='L1Loss'),
        loss_cls=dict(
            alpha=0.25,
            gamma=2.0,
            loss_weight=2.0,
            type='FocalLoss',
            use_sigmoid=True),
        loss_iou=dict(loss_weight=0.0, type='GIoULoss'),
        num_classes=10,
        num_query=900,
        positional_encoding=dict(
            col_num_embed=200,
            num_feats=128,
            row_num_embed=200,
            type='LearnedPositionalEncoding'),
        sync_cls_avg_factor=True,
        transformer=dict(
            decoder=dict(
                num_layers=6,
                return_intermediate=True,
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            dropout=0.1,
                            embed_dims=256,
                            num_heads=8,
                            type='MultiheadAttention'),
                        dict(
                            embed_dims=256,
                            num_levels=1,
                            type='CustomMSDeformableAttention'),
                    ],
                    feedforward_channels=512,
                    ffn_dropout=0.1,
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='MyCustomBaseTransformerLayer'),
                type='DetectionTransformerDecoder'),
            embed_dims=256,
            encoder=dict(
                num_layers=6,
                num_points_in_pillar=4,
                pc_range=[
                    -51.2,
                    -51.2,
                    -5.0,
                    51.2,
                    51.2,
                    3.0,
                ],
                return_intermediate=False,
                transformerlayers=dict(
                    attn_cfgs=[
                        dict(
                            embed_dims=256,
                            num_levels=1,
                            type='TemporalSelfAttention'),
                        dict(
                            deformable_attention=dict(
                                embed_dims=256,
                                num_levels=4,
                                num_points=8,
                                type='MSDeformableAttention3D'),
                            embed_dims=256,
                            pc_range=[
                                -51.2,
                                -51.2,
                                -5.0,
                                51.2,
                                51.2,
                                3.0,
                            ],
                            type='SpatialCrossAttention'),
                    ],
                    feedforward_channels=512,
                    ffn_dropout=0.1,
                    operation_order=(
                        'self_attn',
                        'norm',
                        'cross_attn',
                        'norm',
                        'ffn',
                        'norm',
                    ),
                    type='BEVFormerLayer'),
                type='BEVFormerEncoder'),
            rotate_prev_bev=True,
            type='PerceptionTransformer',
            use_can_bus=True,
            use_shift=True),
        type='BEVFormerHead',
        with_box_refine=True),
    train_cfg=dict(
        pts=dict(
            assigner=dict(
                cls_cost=dict(type='FocalLossCost', weight=2.0),
                iou_cost=dict(type='IoUCost', weight=0.0),
                pc_range=[
                    -51.2,
                    -51.2,
                    -5.0,
                    51.2,
                    51.2,
                    3.0,
                ],
                reg_cost=dict(type='BBox3DL1Cost', weight=0.25),
                type='HungarianAssigner3D'),
            grid_size=[
                512,
                512,
                1,
            ],
            out_size_factor=4,
            point_cloud_range=[
                -51.2,
                -51.2,
                -5.0,
                51.2,
                51.2,
                3.0,
            ],
            voxel_size=[
                0.2,
                0.2,
                8,
            ])),
    type='BEVFormer',
    use_grid_mask=True,
    video_test_mode=True)
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(lr=0.0002, type='AdamW', weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys=dict({
            'depth_adapter': dict(lr_mult=1.0),
            'img_backbone': dict(lr_mult=0.0),
            'img_neck': dict(lr_mult=0.0),
            'pts_bbox_head': dict(lr_mult=0.0),
            'pts_bbox_head.transformer.encoder': dict(lr_mult=0.0)
        })),
    type='OptimWrapper')
optimizer = dict(
    lr=0.0002,
    paramwise_cfg=dict(custom_keys=dict(img_backbone=dict(lr_mult=0.1))),
    type='AdamW',
    weight_decay=0.01)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
plugin = True
plugin_dir = 'projects/mmdet3d_plugin/'
point_cloud_range = [
    -51.2,
    -51.2,
    -5.0,
    51.2,
    51.2,
    3.0,
]
queue_length = 4
resume_from = None
runner = dict(max_epochs=24, type='EpochBasedRunner')
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='C:/datasets/nuscenes/nuscenes_infos_temporal_val.pkl',
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        data_root='C:/datasets/nuscenes/',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        pipeline=[
            dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    1.0,
                    1.0,
                    1.0,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                ],
                meta_keys=[
                    'filename',
                    'ori_shape',
                    'img_shape',
                    'lidar2img',
                    'cam2img',
                    'lidar2cam',
                    'pad_shape',
                    'scale_factor',
                    'flip',
                    'box_mode_3d',
                    'box_type_3d',
                    'img_norm_cfg',
                    'scene_token',
                    'can_bus',
                    'sample_idx',
                    'prev_bev_exists',
                ],
                type='Pack3DDetInputs'),
        ],
        queue_length=1,
        serialize_data=False,
        test_mode=True,
        type='CustomNuScenesDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file=
    'C:/datasets/nuscenes/nuscenes_infos_temporal_val_singapore_datalist.pkl',
    data_root='C:/datasets/nuscenes/',
    metric='bbox',
    type='BEVFormerNuScenesMetric')
test_pipeline = [
    dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
    dict(
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        std=[
            1.0,
            1.0,
            1.0,
        ],
        to_rgb=False,
        type='NormalizeMultiviewImage'),
    dict(size_divisor=32, type='PadMultiViewImage'),
    dict(
        flip=False,
        img_scale=(
            1600,
            900,
        ),
        pts_scale_ratio=1,
        transforms=[
            dict(
                class_names=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='DefaultFormatBundle3D',
                with_label=False),
            dict(keys=[
                'img',
            ], type='CustomCollect3D'),
        ],
        type='MultiScaleFlipAug3D'),
]
total_epochs = 24
train_cfg = dict(max_epochs=4, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='E:/bev_research/data/singapore_pseudo_labels_merged.pkl',
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        data_root='C:/datasets/nuscenes/',
        indices=None,
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        pipeline=[
            dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
            dict(type='PhotoMetricDistortionMultiViewImage'),
            dict(
                type='LoadAnnotations3D',
                with_attr_label=False,
                with_bbox_3d=True,
                with_label_3d=True),
            dict(
                point_cloud_range=[
                    -51.2,
                    -51.2,
                    -5.0,
                    51.2,
                    51.2,
                    3.0,
                ],
                type='ObjectRangeFilter'),
            dict(
                classes=[
                    'car',
                    'truck',
                    'construction_vehicle',
                    'bus',
                    'trailer',
                    'barrier',
                    'motorcycle',
                    'bicycle',
                    'pedestrian',
                    'traffic_cone',
                ],
                type='ObjectNameFilter'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    1.0,
                    1.0,
                    1.0,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                    'gt_bboxes_3d',
                    'gt_labels_3d',
                ],
                meta_keys=[
                    'filename',
                    'ori_shape',
                    'img_shape',
                    'lidar2img',
                    'cam2img',
                    'lidar2cam',
                    'pad_shape',
                    'scale_factor',
                    'flip',
                    'box_mode_3d',
                    'box_type_3d',
                    'img_norm_cfg',
                    'scene_token',
                    'can_bus',
                    'sample_idx',
                    'prev_bev_exists',
                ],
                type='Pack3DDetInputs'),
        ],
        queue_length=4,
        serialize_data=False,
        test_mode=False,
        type='CustomNuScenesDataset',
        use_valid_flag=True),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
    dict(type='PhotoMetricDistortionMultiViewImage'),
    dict(
        type='LoadAnnotations3D',
        with_attr_label=False,
        with_bbox_3d=True,
        with_label_3d=True),
    dict(
        point_cloud_range=[
            -51.2,
            -51.2,
            -5.0,
            51.2,
            51.2,
            3.0,
        ],
        type='ObjectRangeFilter'),
    dict(
        classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        type='ObjectNameFilter'),
    dict(
        mean=[
            103.53,
            116.28,
            123.675,
        ],
        std=[
            1.0,
            1.0,
            1.0,
        ],
        to_rgb=False,
        type='NormalizeMultiviewImage'),
    dict(size_divisor=32, type='PadMultiViewImage'),
    dict(
        class_names=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ],
        type='DefaultFormatBundle3D'),
    dict(
        keys=[
            'gt_bboxes_3d',
            'gt_labels_3d',
            'img',
        ], type='CustomCollect3D'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file=
        'C:/datasets/nuscenes/nuscenes_infos_temporal_val_singapore_datalist.pkl',
        bev_size=(
            200,
            200,
        ),
        box_type_3d='LiDAR',
        data_root='C:/datasets/nuscenes/',
        metainfo=dict(classes=[
            'car',
            'truck',
            'construction_vehicle',
            'bus',
            'trailer',
            'barrier',
            'motorcycle',
            'bicycle',
            'pedestrian',
            'traffic_cone',
        ]),
        modality=dict(
            use_camera=True,
            use_external=True,
            use_lidar=False,
            use_map=False,
            use_radar=False),
        pipeline=[
            dict(to_float32=True, type='LoadMultiViewImageFromFiles'),
            dict(
                mean=[
                    103.53,
                    116.28,
                    123.675,
                ],
                std=[
                    1.0,
                    1.0,
                    1.0,
                ],
                to_rgb=False,
                type='NormalizeMultiviewImage'),
            dict(size_divisor=32, type='PadMultiViewImage'),
            dict(
                keys=[
                    'img',
                ],
                meta_keys=[
                    'filename',
                    'ori_shape',
                    'img_shape',
                    'lidar2img',
                    'cam2img',
                    'lidar2cam',
                    'pad_shape',
                    'scale_factor',
                    'flip',
                    'box_mode_3d',
                    'box_type_3d',
                    'img_norm_cfg',
                    'scene_token',
                    'can_bus',
                    'sample_idx',
                    'prev_bev_exists',
                ],
                type='Pack3DDetInputs'),
        ],
        queue_length=1,
        serialize_data=False,
        test_mode=True,
        type='CustomNuScenesDataset'),
    num_workers=4,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file=
    'C:/datasets/nuscenes/nuscenes_infos_temporal_val_singapore_datalist.pkl',
    data_root='C:/datasets/nuscenes/',
    metric='bbox',
    type='BEVFormerNuScenesMetric')
voxel_size = [
    0.2,
    0.2,
    8,
]
work_dir = 'E:\\bev_research\\work_dirs\\e5_pseudo_label_adapter'
workflow = [
    (
        'train',
        1,
    ),
]
