"""
E5: Pseudo-label adapter training — Singapore target-domain supervision.

What this config does:
  - Inherits the full BEVFormer + DAv2 adapter setup from bevformer_rtx5060_residual01.py
  - Replaces the training data source with Singapore pseudo-labels (target domain)
  - Keeps BEVFormer fully frozen; only adapter layers train
  - Evaluates on Singapore split to directly measure the domain gap

FIX vs. guide original:
  The guide had an invalid Python expression `pipeline=_base_[0].train_pipeline`
  which treats _base_ (a list of filename strings) as Python module objects.
  mmengine config inheritance does NOT work this way and would crash at parse time.
  Instead, we inherit from the existing residual01 config which already has the
  correct pipeline defined, and only override what changes (data source and optimizer).

Prerequisite:
  Run generate_pseudo_labels.py first to produce:
    E:\bev_research\data\singapore_pseudo_labels.pkl

Training command:
    conda activate bev310
    cd E:\Auto_Image\bev_research\mmdetection3d
    python tools\train.py E:\bev_research\configs\adapter\e5_pseudo_label_adapter.py `
        --work-dir E:\bev_research\work_dirs\e5_pseudo_label_adapter

Evaluation command (after training):
    python tools\test.py E:\bev_research\configs\adapter\e5_pseudo_label_adapter.py `
        E:\bev_research\work_dirs\e5_pseudo_label_adapter\epoch_4.pth
"""

# Inherit from the residual01 adapter config (has correct adapter arch, pipeline, etc.)
_base_ = ['../bevformer_rtx5060_residual01_subset2k.py']

# ── Training data: Singapore pseudo-labels ────────────────────────────────────
# Note: the training PKL must have been generated by generate_pseudo_labels.py.
# Pseudo labels follow the same dict structure as real GT (gt_boxes, gt_labels),
# so no dataset code changes are needed.
data_root = 'C:/datasets/nuscenes/'

train_dataloader = dict(
    batch_size=1,
    num_workers=2,
    dataset=dict(
        # Use the merged PKL — original metadata + pseudo-label GT boxes
        ann_file=r'E:/bev_research/data/singapore_pseudo_labels_merged.pkl',
        data_root=data_root,
        # Remove the subset index — train on ALL Singapore pseudo-labels (~2929 frames)
        indices=None,
    ),
)

# ── Evaluation on Singapore split ────────────────────────────────────────────
val_dataloader = dict(
    dataset=dict(
        ann_file=data_root + 'nuscenes_infos_temporal_val_singapore_datalist.pkl',
        data_root=data_root,
    ),
)
val_evaluator = dict(
    type='BEVFormerNuScenesMetric',
    data_root=data_root,
    ann_file=data_root + 'nuscenes_infos_temporal_val_singapore_datalist.pkl',
    metric='bbox',
)
test_evaluator  = val_evaluator
test_dataloader = val_dataloader

# ── Model: frozen BEVFormer + trainable adapter (adapter lr=2e-4 only) ────────
model = dict(
    freeze_bevformer=True,          # backbone, neck, head all frozen
    depth_adapter=dict(
        residual_scale=0.1,         # same as E3-B
        consistency_weight=0.0,     # no consistency loss (supervision from pseudo-labels)
    ),
)

# ── Optimizer: only adapter layers receive a non-zero lr ─────────────────────
optim_wrapper = dict(
    _delete_=True,
    type='OptimWrapper',            # FP32 (avoids fp16 instability during training)
    optimizer=dict(type='AdamW', lr=2e-4, weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys={
            'img_backbone':                       dict(lr_mult=0.0),
            'img_neck':                           dict(lr_mult=0.0),
            'pts_bbox_head':                      dict(lr_mult=0.0),
            'pts_bbox_head.transformer.encoder':  dict(lr_mult=0.0),
            'depth_adapter':                      dict(lr_mult=1.0),
        }
    ),
    clip_grad=dict(max_norm=35, norm_type=2),
)

# ── Training schedule: 4 epochs (same as all prior adapter experiments) ───────
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=4, val_interval=1)
default_hooks = dict(
    logger=dict(type='LoggerHook', interval=50),
    checkpoint=dict(type='CheckpointHook', interval=1, max_keep_ckpts=4),
)

# ── Work directory ────────────────────────────────────────────────────────────
work_dir = r'E:\bev_research\work_dirs\e5_pseudo_label_adapter'

# ── Remove the AdapterDebugHook (its run_id is specific to prior experiments) ─
custom_hooks = []
